name: Deploy CodeIgniter to IIS on Windows Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        - name: Copy CodeIgniter code to IIS root
          shell: pwsh
          run: |
            $source = "${{ github.workspace }}"
            $target = "C:\inetpub\wwwroot\codeigniter"
  
            if (!(Test-Path $target)) {
              New-Item -ItemType Directory -Path $target
            }
  
            robocopy $source $target /E /XO /XN /XC /XD .git .github /XF .env.example .gitattributes
            $rc = $LASTEXITCODE
            Write-Host "Robocopy exit code: $rc"
  
            if ($rc -lt 8) {
              exit 0
            } else {
              Write-Error "Robocopy failed with exit code $rc"
              exit $rc
            }

      - name: Set folder permissions (optional)
        run: |
          icacls "C:\inetpub\wwwroot\codeigniter\writable" /grant "IIS_IUSRS:(OI)(CI)F" /T
