name: Deploy Laravel to IIS on Windows Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment path for PHP and Composer
        run: |
          $env:Path += ";C:\php;C:\ProgramData\ComposerSetup\bin"
          php -v
          composer -V

      - name: Install Laravel dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Copy code to IIS root
        run: |
          $source = "${{ github.workspace }}"
          $target = "C:\inetpub\wwwroot\laravel"

          # Create folder if not exists
          if (!(Test-Path $target)) {
            New-Item -ItemType Directory -Path $target
          }

          # Copy files except .git
          robocopy $source $target /MIR /XD .git .github /XF .env.example .gitattributes

      - name: Laravel setup
        run: |
          cd C:\inetpub\wwwroot\laravel
          cp .env.production .env  # or create dynamically
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Set folder permissions (optional)
        run: |
          icacls "C:\inetpub\wwwroot\laravel\storage" /grant "IIS_IUSRS:(OI)(CI)F" /T
          icacls "C:\inetpub\wwwroot\laravel\bootstrap\cache" /grant "IIS_IUSRS:(OI)(CI)F" /T

      - name: Restart IIS (optional)
        run: iisreset
